Repository shoesbox/shoesbox-be, pull requests merged in 2022-10, with the labels that each got.

#129 feature : 게시물 길이 제한
  src/main/java/com/shoesbox/domain/post/Post.java
Labels: enhancement

#132 style: Reformat code
  build.gradle
  img/logo.png
  readme.md
  src/main/java/com/shoesbox/domain/member/MemberService.java
  src/main/java/com/shoesbox/domain/photo/Photo.java
  src/main/java/com/shoesbox/domain/photo/S3Service.java
  src/main/java/com/shoesbox/domain/photo/exception/ImageConvertFailureException.java
  src/main/java/com/shoesbox/domain/photo/exception/ImageDeleteFailureException.java
  src/main/java/com/shoesbox/domain/photo/exception/ImageDownloadFailureException.java
  src/main/java/com/shoesbox/domain/photo/exception/ImageUploadFailureException.java
  src/main/java/com/shoesbox/domain/post/PostService.java
  src/main/java/com/shoesbox/domain/post/dto/PostResponseDto.java
  src/main/java/com/shoesbox/domain/post/dto/PostUpdateDto.java
  src/main/java/com/shoesbox/domain/post/exception/FileCountLimitExceededException.java
  src/main/java/com/shoesbox/global/exception/RestExceptionHandler.java
  src/main/java/com/shoesbox/global/exception/apierror/ApiError.java
  src/main/java/com/shoesbox/global/util/ImageUtil.java
  src/main/resources/application.yml
Labels: bug, enhancement

#133 Feature/131 guestlogin add admin
  src/main/java/com/shoesbox/domain/guest/GuestController.java
  src/main/java/com/shoesbox/domain/guest/GuestService.java
Labels: enhancement

#134 Bugfix/130 overall image uploading bug fix
  build.gradle
  readme.md
  src/main/java/com/shoesbox/domain/member/MemberService.java
  src/main/java/com/shoesbox/domain/photo/S3Service.java
  src/main/java/com/shoesbox/domain/post/Post.java
  src/main/java/com/shoesbox/domain/post/PostController.java
  src/main/java/com/shoesbox/domain/post/PostService.java
  src/main/java/com/shoesbox/domain/social/OAuthRequestFactory.java
  src/main/java/com/shoesbox/global/config/SecurityConfig.java
  src/main/java/com/shoesbox/global/util/ImageUtil.java
Labels: bug

#135 fix: 이미지 업로드 버그 수정
  src/main/java/com/shoesbox/domain/member/MemberService.java
  src/main/java/com/shoesbox/domain/photo/exception/ImageConvertFailureException.java
  src/main/java/com/shoesbox/domain/photo/exception/ImageDeleteFailureException.java
  src/main/java/com/shoesbox/domain/photo/exception/ImageDownloadFailureException.java
  src/main/java/com/shoesbox/domain/photo/exception/ImageUploadFailureException.java
  src/main/java/com/shoesbox/domain/post/PostController.java
  src/main/java/com/shoesbox/domain/post/PostService.java
  src/main/java/com/shoesbox/global/exception/ExceptionCode.java
  src/main/java/com/shoesbox/global/exception/GlobalExceptionHandler.java
  src/main/java/com/shoesbox/global/exception/RestExceptionHandler.java
  src/main/java/com/shoesbox/global/exception/apierror/ApiError.java
  src/main/java/com/shoesbox/global/exception/runtime/image/ImageConvertFailureException.java
  src/main/java/com/shoesbox/global/exception/runtime/image/ImageDeleteFailureException.java
  src/main/java/com/shoesbox/global/exception/runtime/image/ImageDownloadFailureException.java
  src/main/java/com/shoesbox/global/exception/runtime/image/ImageProcessException.java
  src/main/java/com/shoesbox/global/exception/runtime/image/ImageUploadFailureException.java
  src/main/java/com/shoesbox/global/util/ImageUtil.java
  src/main/java/com/shoesbox/global/util/S3Util.java
Labels: bug, enhancement, refactor

#138 fix: Orientation 정보가 없는 이미지를 업로드할 수 없는 버그 수정
  src/main/java/com/shoesbox/global/util/ImageUtil.java
Labels: bug
