Repository shoesbox/shoesbox-be, pull requests merged in 2022-09, with the labels that each got.

#23 feature/22 JWT를 사용한 로그인, 회원가입
  .gitignore
  build.gradle
  src/main/java/com/shoesbox/comment/CommentController.java
  src/main/java/com/shoesbox/comment/CommentRequestDto.java
  src/main/java/com/shoesbox/comment/CommentResponseDto.java
  src/main/java/com/shoesbox/comment/CommentService.java
  src/main/java/com/shoesbox/domain/auth/RefreshToken.java
  src/main/java/com/shoesbox/domain/auth/RefreshTokenRepository.java
  src/main/java/com/shoesbox/domain/auth/TokenDto.java
  src/main/java/com/shoesbox/domain/auth/TokenRequestDto.java
  src/main/java/com/shoesbox/domain/comment/Comment.java
  src/main/java/com/shoesbox/domain/comment/CommentController.java
  src/main/java/com/shoesbox/domain/comment/CommentRepository.java
  src/main/java/com/shoesbox/domain/comment/CommentRequestDto.java
  src/main/java/com/shoesbox/domain/comment/CommentResponseDto.java
  src/main/java/com/shoesbox/domain/comment/CommentService.java
  src/main/java/com/shoesbox/domain/member/Member.java
  src/main/java/com/shoesbox/domain/member/MemberController.java
  src/main/java/com/shoesbox/domain/member/MemberRepository.java
  src/main/java/com/shoesbox/domain/member/MemberService.java
  src/main/java/com/shoesbox/domain/member/dto/MemberInfoDto.java
  src/main/java/com/shoesbox/domain/member/dto/SignDto.java
  src/main/java/com/shoesbox/domain/post/Post.java
  src/main/java/com/shoesbox/domain/post/PostController.java
  src/main/java/com/shoesbox/domain/post/PostRepository.java
  src/main/java/com/shoesbox/domain/post/PostService.java
  src/main/java/com/shoesbox/domain/post/dto/PostListResponseDto.java
  src/main/java/com/shoesbox/domain/post/dto/PostRequestDto.java
  src/main/java/com/shoesbox/domain/post/dto/PostResponseDto.java
  src/main/java/com/shoesbox/global/common/BaseTimeEntity.java
  src/main/java/com/shoesbox/global/common/ResponseHandler.java
  src/main/java/com/shoesbox/global/config/SecurityConfig.java
  src/main/java/com/shoesbox/global/exception/RestExceptionHandler.java
  src/main/java/com/shoesbox/global/exception/apierror/ApiError.java
  src/main/java/com/shoesbox/global/security/CustomUserDetails.java
  src/main/java/com/shoesbox/global/security/CustomUserDetailsService.java
  src/main/java/com/shoesbox/global/security/jwt/ExceptionCode.java
  src/main/java/com/shoesbox/global/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/shoesbox/global/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/shoesbox/global/security/jwt/JwtFilter.java
  src/main/java/com/shoesbox/global/security/jwt/TokenProvider.java
  src/main/java/com/shoesbox/global/util/SecurityUtil.java
  src/main/java/com/shoesbox/post/PostController.java
  src/main/java/com/shoesbox/post/PostResponseDto.java
  src/main/java/com/shoesbox/post/PostService.java
  src/main/resources/application.yml
Labels: enhancement

#27 fix: Fix request and response value, authorization
  src/main/java/com/shoesbox/domain/comment/Comment.java
  src/main/java/com/shoesbox/domain/comment/CommentController.java
  src/main/java/com/shoesbox/domain/comment/CommentRequestDto.java
  src/main/java/com/shoesbox/domain/comment/CommentResponseDto.java
  src/main/java/com/shoesbox/domain/comment/CommentService.java
  src/main/java/com/shoesbox/domain/member/MemberService.java
  src/main/java/com/shoesbox/domain/post/Post.java
  src/main/java/com/shoesbox/domain/post/PostController.java
  src/main/java/com/shoesbox/domain/post/PostService.java
  src/main/java/com/shoesbox/domain/post/dto/PostListResponseDto.java
  src/main/java/com/shoesbox/domain/post/dto/PostRequestDto.java
  src/main/java/com/shoesbox/global/config/SecurityConfig.java
Labels: bug

#28 refactor: Refactor coupling
  src/main/java/com/shoesbox/domain/comment/Comment.java
  src/main/java/com/shoesbox/domain/comment/CommentController.java
  src/main/java/com/shoesbox/domain/comment/CommentRequestDto.java
  src/main/java/com/shoesbox/domain/comment/CommentResponseDto.java
  src/main/java/com/shoesbox/domain/comment/CommentService.java
  src/main/java/com/shoesbox/domain/member/MemberService.java
  src/main/java/com/shoesbox/domain/post/Post.java
  src/main/java/com/shoesbox/domain/post/PostController.java
  src/main/java/com/shoesbox/domain/post/PostService.java
  src/main/java/com/shoesbox/domain/post/dto/PostListResponseDto.java
  src/main/java/com/shoesbox/domain/post/dto/PostRequestDto.java
  src/main/java/com/shoesbox/global/config/SecurityConfig.java
Labels: enhancement

#30 Feature/18 friend management
  src/main/java/com/shoesbox/domain/friend/Friend.java
  src/main/java/com/shoesbox/domain/friend/FriendController.java
  src/main/java/com/shoesbox/domain/friend/FriendRepository.java
  src/main/java/com/shoesbox/domain/friend/FriendService.java
  src/main/java/com/shoesbox/domain/friend/FriendState.java
  src/main/java/com/shoesbox/domain/friend/dto/FriendListResponseDto.java
  src/main/java/com/shoesbox/domain/friend/dto/FriendRequestDto.java
Labels: enhancement

#31 feat: Add get member info
  src/main/java/com/shoesbox/domain/member/MemberController.java
  src/main/java/com/shoesbox/domain/member/MemberService.java
  src/main/java/com/shoesbox/global/util/SecurityUtil.java
Labels: enhancement

#32 Feature/18 friend exception
  src/main/java/com/shoesbox/domain/friend/Friend.java
  src/main/java/com/shoesbox/domain/friend/FriendController.java
  src/main/java/com/shoesbox/domain/friend/FriendRepository.java
  src/main/java/com/shoesbox/domain/friend/FriendService.java
  src/main/java/com/shoesbox/domain/friend/FriendState.java
  src/main/java/com/shoesbox/domain/friend/dto/FriendListResponseDto.java
  src/main/java/com/shoesbox/domain/friend/dto/FriendResponseDto.java
  src/main/java/com/shoesbox/domain/post/PostService.java
Labels: enhancement

#37 Feature/36 bugfix
  src/main/java/com/shoesbox/ShoesBoxApplication.java
  src/main/java/com/shoesbox/domain/auth/TokenDto.java
  src/main/java/com/shoesbox/domain/comment/CommentService.java
  src/main/java/com/shoesbox/global/security/jwt/TokenProvider.java
Labels: bug

#38 feat: Add getPosts by member and date
  src/main/java/com/shoesbox/domain/post/PostController.java
  src/main/java/com/shoesbox/domain/post/PostRepository.java
  src/main/java/com/shoesbox/domain/post/PostService.java
Labels: enhancement

#41 feat: Add delete account
  src/main/java/com/shoesbox/domain/member/MemberController.java
  src/main/java/com/shoesbox/domain/member/MemberService.java
Labels: enhancement

#44 refactor: Refactor issue jwt
  src/main/java/com/shoesbox/domain/auth/RefreshToken.java
  src/main/java/com/shoesbox/domain/auth/TokenDto.java
  src/main/java/com/shoesbox/domain/member/MemberController.java
  src/main/java/com/shoesbox/domain/member/MemberService.java
  src/main/java/com/shoesbox/global/security/CustomUserDetails.java
  src/main/java/com/shoesbox/global/security/CustomUserDetailsService.java
  src/main/java/com/shoesbox/global/security/jwt/TokenProvider.java
Labels: refactor

#45 feat: Add default profile image
  src/main/java/com/shoesbox/domain/member/MemberService.java
Labels: enhancement

#47 feat: Add update member info
  src/main/java/com/shoesbox/domain/member/MemberController.java
  src/main/java/com/shoesbox/domain/member/MemberService.java
  src/main/java/com/shoesbox/domain/member/dto/MemberInfoResponseDto.java
  src/main/java/com/shoesbox/domain/member/dto/MemberInfoUpdateDto.java
  src/main/java/com/shoesbox/domain/post/PostService.java
Labels: enhancement

#51 refactor: Refactor post response and exception
  src/main/java/com/shoesbox/domain/member/MemberService.java
  src/main/java/com/shoesbox/domain/post/PostService.java
  src/main/java/com/shoesbox/domain/post/dto/PostResponseDto.java
Labels: refactor

#53 Feature/34 login social
  build.gradle
  src/main/java/com/shoesbox/domain/social/OAuthRequest.java
  src/main/java/com/shoesbox/domain/social/OAuthRequestFactory.java
  src/main/java/com/shoesbox/domain/social/ProviderService.java
  src/main/java/com/shoesbox/domain/social/SocialController.java
  src/main/java/com/shoesbox/domain/social/dto/GoogleProfile.java
  src/main/java/com/shoesbox/domain/social/dto/KakaoProfile.java
  src/main/java/com/shoesbox/domain/social/dto/NaverProfile.java
  src/main/java/com/shoesbox/domain/social/dto/ProfileDto.java
  src/main/java/com/shoesbox/global/config/SecurityConfig.java
Labels: enhancement

#56 회원탈퇴 관련 버그 수정
  src/main/java/com/shoesbox/domain/comment/CommentController.java
  src/main/java/com/shoesbox/domain/friend/FriendService.java
  src/main/java/com/shoesbox/domain/member/Member.java
  src/main/java/com/shoesbox/domain/member/MemberController.java
  src/main/java/com/shoesbox/domain/post/PostController.java
  src/main/java/com/shoesbox/global/util/SecurityUtil.java
Labels: bug

#54 refactor: Modify post response
  src/main/java/com/shoesbox/domain/post/Post.java
  src/main/java/com/shoesbox/domain/post/PostService.java
  src/main/java/com/shoesbox/domain/post/dto/PostResponseDto.java
Labels: refactor

#63 fix: Fix member info update without image file
  src/main/java/com/shoesbox/domain/member/Member.java
  src/main/java/com/shoesbox/domain/member/MemberController.java
  src/main/java/com/shoesbox/domain/member/MemberService.java
  src/main/java/com/shoesbox/domain/member/dto/MemberInfoResponseDto.java
  src/main/java/com/shoesbox/domain/member/dto/MemberInfoUpdateDto.java
  src/main/java/com/shoesbox/domain/social/ProviderService.java
Labels: bug

#64 Feature/59 friend bug
  src/main/java/com/shoesbox/domain/friend/FriendController.java
  src/main/java/com/shoesbox/domain/friend/FriendRepository.java
  src/main/java/com/shoesbox/domain/friend/FriendService.java
  src/main/java/com/shoesbox/domain/friend/dto/FriendListResponseDto.java
Labels: bug

#65 Feature/57 friend access
  src/main/java/com/shoesbox/domain/comment/CommentController.java
  src/main/java/com/shoesbox/domain/comment/CommentService.java
  src/main/java/com/shoesbox/domain/friend/FriendRepository.java
  src/main/java/com/shoesbox/domain/friend/FriendService.java
  src/main/java/com/shoesbox/domain/post/PostController.java
  src/main/java/com/shoesbox/domain/post/PostService.java
Labels: enhancement

#61 feature : s3 상의 이미지 수정 및 삭제
  src/main/java/com/shoesbox/domain/photo/PhotoRepository.java
  src/main/java/com/shoesbox/domain/photo/S3Service.java
  src/main/java/com/shoesbox/domain/post/PostController.java
  src/main/java/com/shoesbox/domain/post/PostService.java
  src/main/java/com/shoesbox/domain/post/dto/PostResponseDto.java
Labels: enhancement

#68 Fix: fix Post number limit
  src/main/java/com/shoesbox/domain/post/PostController.java
  src/main/java/com/shoesbox/domain/post/PostRepository.java
  src/main/java/com/shoesbox/domain/post/PostService.java
Labels: bug

#71 feat: 회원 프로필 사진 초기화
  src/main/java/com/shoesbox/domain/member/MemberController.java
  src/main/java/com/shoesbox/domain/member/MemberService.java
Labels: enhancement

#72 feat: 일기 목록 반환 형태 변경
  src/main/java/com/shoesbox/domain/post/Post.java
  src/main/java/com/shoesbox/domain/post/PostController.java
  src/main/java/com/shoesbox/domain/post/PostRepository.java
  src/main/java/com/shoesbox/domain/post/PostService.java
  src/main/java/com/shoesbox/domain/post/dto/PostListResponseDto.java
  src/main/java/com/shoesbox/domain/post/dto/PostResponseDto.java
  src/main/java/com/shoesbox/global/security/CustomUserDetails.java
  src/main/java/com/shoesbox/global/security/CustomUserDetailsService.java
  src/main/java/com/shoesbox/global/security/jwt/TokenProvider.java
Labels: enhancement

#80 Bugfix/81 image thumbnail
  build.gradle
  src/main/java/com/shoesbox/domain/photo/S3Service.java
  src/main/java/com/shoesbox/domain/post/Post.java
  src/main/java/com/shoesbox/domain/post/PostService.java
Labels: bug

#79 feat: Add Friend Request List
  src/main/java/com/shoesbox/domain/friend/FriendController.java
  src/main/java/com/shoesbox/domain/friend/FriendRepository.java
  src/main/java/com/shoesbox/domain/friend/FriendService.java
Labels: enhancement

#84 fix: 마지막 날 계산이 잘못 이루어지던 문제 해결
  src/main/java/com/shoesbox/domain/post/PostController.java
Labels: bug

#89 feat: Modify post update
  src/main/java/com/shoesbox/domain/post/Post.java
  src/main/java/com/shoesbox/domain/post/PostController.java
  src/main/java/com/shoesbox/domain/post/PostService.java
Labels: enhancement

#90 fix: Fix comment create
  src/main/java/com/shoesbox/domain/comment/CommentService.java
Labels: bug

#93 refactor: Refactor overall
  src/main/java/com/shoesbox/domain/auth/CustomUserDetails.java
  src/main/java/com/shoesbox/domain/auth/CustomUserDetailsService.java
  src/main/java/com/shoesbox/domain/auth/RedisService.java
  src/main/java/com/shoesbox/domain/auth/dto/TokenRequestDto.java
  src/main/java/com/shoesbox/domain/auth/dto/TokenResponseDto.java
  src/main/java/com/shoesbox/domain/comment/Comment.java
  src/main/java/com/shoesbox/domain/comment/CommentController.java
  src/main/java/com/shoesbox/domain/comment/CommentRepository.java
  src/main/java/com/shoesbox/domain/comment/CommentService.java
  src/main/java/com/shoesbox/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/shoesbox/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/shoesbox/domain/friend/FriendController.java
  src/main/java/com/shoesbox/domain/friend/exception/DuplicateFriendRequestException.java
  src/main/java/com/shoesbox/domain/member/Member.java
  src/main/java/com/shoesbox/domain/member/MemberController.java
  src/main/java/com/shoesbox/domain/member/MemberService.java
  src/main/java/com/shoesbox/domain/member/dto/SignDto.java
  src/main/java/com/shoesbox/domain/member/exception/DuplicateUserInfoException.java
  src/main/java/com/shoesbox/domain/post/Post.java
  src/main/java/com/shoesbox/domain/post/PostController.java
  src/main/java/com/shoesbox/domain/post/PostRepository.java
  src/main/java/com/shoesbox/domain/post/PostService.java
  src/main/java/com/shoesbox/domain/post/dto/PostRequestDto.java
  src/main/java/com/shoesbox/domain/post/dto/PostResponseDto.java
  src/main/java/com/shoesbox/domain/post/dto/PostResponseListDto.java
  src/main/java/com/shoesbox/domain/post/dto/PostUpdateDto.java
  src/main/java/com/shoesbox/domain/social/ProviderService.java
  src/main/java/com/shoesbox/global/config/RedisConfig.java
  src/main/java/com/shoesbox/global/config/SecurityConfig.java
  src/main/java/com/shoesbox/global/config/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/shoesbox/global/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/shoesbox/global/config/jwt/JwtExceptionCode.java
  src/main/java/com/shoesbox/global/config/jwt/JwtFilter.java
  src/main/java/com/shoesbox/global/config/jwt/JwtProvider.java
  src/main/java/com/shoesbox/global/exception/RestExceptionHandler.java
  src/main/java/com/shoesbox/global/exception/runtime/EntityNotFoundException.java
  src/main/java/com/shoesbox/global/exception/runtime/InvalidJwtException.java
  src/main/java/com/shoesbox/global/exception/runtime/PostNotFoundException.java
  src/main/java/com/shoesbox/global/security/jwt/ExceptionCode.java
  src/main/java/com/shoesbox/global/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/shoesbox/global/util/SecurityUtil.java
Labels: bug, enhancement, refactor

#94 fix: Fix friend dto
  src/main/java/com/shoesbox/domain/friend/dto/FriendRequestDto.java
  src/main/java/com/shoesbox/domain/friend/dto/FriendResponseListDto.java
Labels: bug

#95 fix: 전체글 보기 날짜 비교 버그 수정
  src/main/java/com/shoesbox/domain/post/PostService.java
Labels: bug

#96 fix: 전체글 반환값 수정
  src/main/java/com/shoesbox/domain/post/PostService.java
  src/main/java/com/shoesbox/domain/post/dto/PostResponseListDto.java
Labels: enhancement

#97 fix: Fix get posts authorization bug
  src/main/java/com/shoesbox/domain/post/PostService.java
Labels: bug

#100 feat: Add Code Deploy with AWS
  .github/workflows/deploy.yml
  appspec.yml
  build.gradle
  scripts/start.sh
  scripts/stop.sh
Labels: enhancement

#107 feat: Add multi-stage deployments
  .github/workflows/build.yml
  .github/workflows/deploy.yml
Labels: enhancement

#105 Feature/104 bugfix sociallogin
  src/main/java/com/shoesbox/domain/friend/FriendController.java
  src/main/java/com/shoesbox/domain/social/ProviderService.java
  src/main/java/com/shoesbox/domain/social/SocialController.java
  src/main/java/com/shoesbox/domain/social/dto/GoogleProfile.java
  src/main/java/com/shoesbox/domain/social/dto/KakaoProfile.java
  src/main/java/com/shoesbox/domain/social/dto/NaverProfile.java
  src/main/java/com/shoesbox/domain/social/dto/ProfileDto.java
Labels: bug

#110 update: 기존에 작성한 글의 작성자 닉네임 변경이 적용되도록 변경
  scripts/stop.sh
  src/main/java/com/shoesbox/domain/post/Post.java
  src/main/java/com/shoesbox/domain/post/PostController.java
  src/main/java/com/shoesbox/domain/post/PostService.java
Labels: enhancement

#114 Fix: Fix Guest Friend Account make auto
  src/main/java/com/shoesbox/domain/guest/GuestService.java
Labels: bug

#117 feat: 이미지 압축 기능 추가
  build.gradle
  src/main/java/com/shoesbox/domain/guest/GuestService.java
  src/main/java/com/shoesbox/domain/photo/S3Service.java
  src/main/java/com/shoesbox/domain/photo/exception/ImageUploadFailureException.java
  src/main/java/com/shoesbox/domain/post/PostController.java
  src/main/java/com/shoesbox/domain/post/PostService.java
  src/main/java/com/shoesbox/global/config/SecurityConfig.java
  src/main/java/com/shoesbox/global/exception/RestExceptionHandler.java
  src/main/resources/application.yml
Labels: enhancement

#118 fix: 기본 이미지 링크가 잘못 들어가있는 버그 수정
  src/main/java/com/shoesbox/domain/guest/GuestService.java
  src/main/java/com/shoesbox/domain/member/MemberController.java
  src/main/java/com/shoesbox/domain/member/MemberService.java
  src/main/java/com/shoesbox/domain/post/PostService.java
Labels: bug

#119 Feature/111 sse alarm
  src/main/java/com/shoesbox/domain/comment/CommentService.java
  src/main/java/com/shoesbox/domain/member/Member.java
  src/main/java/com/shoesbox/domain/member/MemberService.java
  src/main/java/com/shoesbox/domain/post/PostService.java
  src/main/java/com/shoesbox/domain/sse/Alarm.java
  src/main/java/com/shoesbox/domain/sse/AlarmController.java
  src/main/java/com/shoesbox/domain/sse/AlarmRepository.java
  src/main/java/com/shoesbox/domain/sse/AlarmService.java
  src/main/java/com/shoesbox/domain/sse/MessageDto.java
  src/main/java/com/shoesbox/domain/sse/MessageType.java
  src/main/java/com/shoesbox/domain/sse/SseController.java
  src/main/java/com/shoesbox/domain/sse/dto/AlarmResponseDto.java
  src/main/java/com/shoesbox/global/config/SecurityConfig.java
Labels: enhancement

#121 Bugfix/120 delete synchronize
  src/main/java/com/shoesbox/domain/friend/FriendService.java
  src/main/java/com/shoesbox/domain/sse/AlarmRepository.java
Labels: bug

#123 feat: Add Daily Friend Post
  src/main/java/com/shoesbox/domain/guest/GuestController.java
  src/main/java/com/shoesbox/domain/guest/GuestService.java
  src/main/resources/application.yml
Labels: enhancement
